# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5aa60c8061a04ef37fe57e4307261567e5e125682e420f6a393c62445691fd104feae9d48a4da8cd9d461d5b539e39fbfbb488e03d76a762d59f2a70da921854

test:
  secret_key_base: f67484c3dfcffdd25339c1c34c308e6577351d2384c8cf10b5c170edec9faa0f942d663e246742e4ac9c58a862f23e0b94996d049ccb914897dd9401b357a10f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
